# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CloudfleetCli < Formula
  desc "Cloudfleet Command Line Interface"
  homepage "https://cloudfleet.ai"
  version "0.6.5"

  depends_on "kubernetes-cli" => :recommended

  on_macos do
    url "https://downloads.cloudfleet.ai/cli/0.6.5/cloudfleet_darwin_all.zip"
    sha256 "7608a46f5b8144b5252c41e457fe81c76a86219a730a70b9e2dcca0247fc3a23"

    def install
      bin.install "cloudfleet" => "cloudfleet"

      # Install bash completion
      output = Utils.popen_read("#{bin}/cloudfleet completion bash")
      (bash_completion/"cloudfleet").write output

      # Install zsh completion
      output = Utils.popen_read("#{bin}/cloudfleet completion zsh")
      (zsh_completion/"_cloudfleet").write output
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://downloads.cloudfleet.ai/cli/0.6.5/cloudfleet_linux_amd64.zip"
      sha256 "06d97d6167def31623a3f739eceac7bf517c24a6481e6b2708766a992d5c09c2"
      def install
        bin.install "cloudfleet" => "cloudfleet"

        # Install bash completion
        output = Utils.popen_read("#{bin}/cloudfleet completion bash")
        (bash_completion/"cloudfleet").write output

        # Install zsh completion
        output = Utils.popen_read("#{bin}/cloudfleet completion zsh")
        (zsh_completion/"_cloudfleet").write output
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://downloads.cloudfleet.ai/cli/0.6.5/cloudfleet_linux_arm64.zip"
      sha256 "8c534767bb2520689e348d9ea0878b80aaf59f326c57594c2d04b3a44ac4de19"
      def install
        bin.install "cloudfleet" => "cloudfleet"

        # Install bash completion
        output = Utils.popen_read("#{bin}/cloudfleet completion bash")
        (bash_completion/"cloudfleet").write output

        # Install zsh completion
        output = Utils.popen_read("#{bin}/cloudfleet completion zsh")
        (zsh_completion/"_cloudfleet").write output
      end
    end
  end
end
