# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CloudfleetCli < Formula
  desc "Cloudfleet Command Line Interface"
  homepage "https://cloudfleet.ai"
  version "0.6.32"

  depends_on "kubernetes-cli" => :recommended

  on_macos do
    url "https://downloads.cloudfleet.ai/cli/0.6.32/cloudfleet_darwin_all.zip"
    sha256 "2efb9e3ded10b33eef5150cbde3c4ba199b1d0614e16f2d486e6c8d8f82ddbe4"

    def install
      bin.install "cloudfleet" => "cloudfleet"

      # Docker credential helper symlink
      bin.install_symlink "cloudfleet" => "docker-credential-cloudfleet"

      # Install bash completion
      output = Utils.popen_read("#{bin}/cloudfleet completion bash")
      (bash_completion/"cloudfleet").write output

      # Install zsh completion
      output = Utils.popen_read("#{bin}/cloudfleet completion zsh")
      (zsh_completion/"_cloudfleet").write output
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://downloads.cloudfleet.ai/cli/0.6.32/cloudfleet_linux_amd64.zip"
      sha256 "d2f65bacf125db4618aa8ba97a6c9c0528dcdedf0de30282daf0b4828c86f370"
      def install
        bin.install "cloudfleet" => "cloudfleet"

        # Docker credential helper symlink
        bin.install_symlink "cloudfleet" => "docker-credential-cloudfleet"

        # Install bash completion
        output = Utils.popen_read("#{bin}/cloudfleet completion bash")
        (bash_completion/"cloudfleet").write output

        # Install zsh completion
        output = Utils.popen_read("#{bin}/cloudfleet completion zsh")
        (zsh_completion/"_cloudfleet").write output
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://downloads.cloudfleet.ai/cli/0.6.32/cloudfleet_linux_arm64.zip"
      sha256 "c44bc2699c23a71f77a64dfead3ae0f175de5fbad7a5000c59da1c99e1ff0aa8"
      def install
        bin.install "cloudfleet" => "cloudfleet"

        # Docker credential helper symlink
        bin.install_symlink "cloudfleet" => "docker-credential-cloudfleet"

        # Install bash completion
        output = Utils.popen_read("#{bin}/cloudfleet completion bash")
        (bash_completion/"cloudfleet").write output

        # Install zsh completion
        output = Utils.popen_read("#{bin}/cloudfleet completion zsh")
        (zsh_completion/"_cloudfleet").write output
      end
    end
  end
end
