# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CloudfleetCli < Formula
  desc "Cloudfleet Command Line Interface"
  homepage "https://cloudfleet.ai"
  version "0.8.16"

  depends_on "kubernetes-cli" => :recommended

  on_macos do
    url "https://downloads.cloudfleet.ai/cli/0.8.16/cloudfleet_darwin_all.zip"
    sha256 "ee095c0651df245c87979ce716e6fff653678d70b9d808cd9aeee3cf642807da"

    def install
      bin.install "cloudfleet" => "cloudfleet"

      # Docker credential helper symlink
      bin.install_symlink "cloudfleet" => "docker-credential-cloudfleet"

      # Install bash completion
      output = Utils.popen_read("#{bin}/cloudfleet completion bash")
      (bash_completion/"cloudfleet").write output

      # Install zsh completion
      output = Utils.popen_read("#{bin}/cloudfleet completion zsh")
      (zsh_completion/"_cloudfleet").write output
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://downloads.cloudfleet.ai/cli/0.8.16/cloudfleet_linux_amd64.zip"
      sha256 "b9312cb97e603f75393143398a75d031b6792fac86fe87112e8bc0fde0295ddd"
      def install
        bin.install "cloudfleet" => "cloudfleet"

        # Docker credential helper symlink
        bin.install_symlink "cloudfleet" => "docker-credential-cloudfleet"

        # Install bash completion
        output = Utils.popen_read("#{bin}/cloudfleet completion bash")
        (bash_completion/"cloudfleet").write output

        # Install zsh completion
        output = Utils.popen_read("#{bin}/cloudfleet completion zsh")
        (zsh_completion/"_cloudfleet").write output
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://downloads.cloudfleet.ai/cli/0.8.16/cloudfleet_linux_arm64.zip"
      sha256 "9ad1514fbf8214aea0ae03648c05c00956635eac00e978a7ec48ce783becf243"
      def install
        bin.install "cloudfleet" => "cloudfleet"

        # Docker credential helper symlink
        bin.install_symlink "cloudfleet" => "docker-credential-cloudfleet"

        # Install bash completion
        output = Utils.popen_read("#{bin}/cloudfleet completion bash")
        (bash_completion/"cloudfleet").write output

        # Install zsh completion
        output = Utils.popen_read("#{bin}/cloudfleet completion zsh")
        (zsh_completion/"_cloudfleet").write output
      end
    end
  end
end
